export default [
  {
    id: 'black-leather-jacket',
    itemName: 'Black Leather Jacket',
    imageId: '1Zj-h35UciY',
    qty: 1,
    price: 89.9,
  },
  {
    id: 'woof-hoodie',
    itemName: 'woof Hoodie',
    imageId: '5-jX_6kqsaw',
    qty: 1,
    price: 49.9,
  },
  {
    id: 'beige-t-shirt',
    itemName: 'Beige T-Shirt',
    imageId: 'O4TscN7RnSc',
    qty: 1,
    price: 25.9,
  },
  {
    id: 'denim-overalls-with-straps',
    itemName: 'Denim Overalls with Straps',
    imageId: 'PJTfOzSo8fQ',
    qty: 1,
    price: 69.9,
  },
  {
    id: 'grey-onesie',
    itemName: 'Grey Onesie',
    imageId: 'GVaRGYa_cmk',
    qty: 1,
    price: 59.9,
  },
  {
    id: 'yellow-pom-pom-beanie',
    itemName: 'Yellow Pom Pom Beanie',
    imageId: 'AQRp2NH-O8k',
    qty: 1,
    price: 23.9,
  },
  {
    id: 'french-fries-t-shirt',
    itemName: 'French Fries T-Shirt',
    imageId: 'mftVVfdXomc',
    qty: 1,
    price: 32.9,
  },
  {
    id: 'pink-hoodie',
    itemName: 'Pink Hoodie',
    imageId: 'icoKXy3bDBw',
    qty: 1,
    price: 45.9,
  },
];
